name: earth_and_i
description: "This project visualizes the effects that carbon reduction has on me as part of the process of protecting the Earth."
publish_to: 'none'

version: 1.1.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  # Default
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: any

  # Icon
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1

  # Splash Screen
  flutter_native_splash: ^2.3.6

  # Dotenv
  flutter_dotenv: ^5.1.0

  # Localization And Logger
  intl: ^0.18.1
  logger: ^2.0.2+1

  # GetX
  get: ^4.6.6

  # Svg
  flutter_svg: ^2.0.9

  # Loading Animation
  loading_animation_widget: ^1.2.0+4

  # Speech To Text
  speech_to_text: ^6.6.0

  # Staggered Animation
  flutter_staggered_animations: ^1.0.0

  # Extended Nested Scroll View
  extended_nested_scroll_view: ^6.2.1

  # Local Secure Storage
  get_storage: ^2.1.1

  # Carousel Slider
  carousel_slider: ^4.2.1

  # image_picker
  image_picker: ^1.0.7

  # Time Calendar
  table_calendar: ^3.0.9

  # SQLite3 Database
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  path: ^1.8.3

  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5

  # OAuth2
  google_sign_in: ^6.2.1

  # Permission And Health
  permission_handler: ^11.2.1
  health: ^8.1.0

  # Animation
  rive: ^0.12.4
  animated_text_kit: ^4.2.2
  smooth_page_indicator: ^1.1.0

  # Native Widget
  home_widget: ^0.4.1

  # Notification
  timezone: ^0.9.2
  flutter_app_badger: ^1.5.0
  flutter_local_notifications: ^16.3.2
  firebase_messaging: ^14.7.16


dev_dependencies:
  # Default
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Localization
  intl_translation: ^0.18.1

  # SQLite3 Database
  drift_dev: ^2.14.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/character/
    - assets/images/analysis/
    - assets/images/on_boarding/
    - assets/images/thumbnail/
    - assets/icons/
    - assets/riv/
    - assets/config/.env

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
